name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate Formatting
        run: cargo fmt --check --message-format=human

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  validate:
    name: Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate shell scripts
        uses: ludeeus/action-shellcheck@master
        if: ${{ ! cancelled() }}
        with:
          check_together: 'yes'
          scandir: ./scripts
