name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and run tests (${{ matrix.name }})
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux amd64
            runner: ubuntu-24.04
          - name: linux aarch64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure LLVM
        shell: bash
        run: . ./scripts/setup-llvm.sh

      - name: Build
        shell: bash
        run: cargo build --verbose

      - name: Run tests
        shell: bash
        run: cargo test --verbose

  validate:
    name: Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate Formatting
        if: ${{ ! cancelled() }}
        run: cargo fmt --check --message-format=human

      - name: Validate shell scripts
        uses: ludeeus/action-shellcheck@master
        if: ${{ ! cancelled() }}
        with:
          check_together: 'yes'
          scandir: ./scripts
